# Generated by Django 3.1.4 on 2021-12-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.category'),
        ),
    ]
